// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import Footer from "./components/footer";
import Header from "./components/header";
import { UserProvider } from "./context/UserContext";


export const metadata: Metadata = {
  title: "fortune 400",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="min-h-screen">
          <Header />
          <NavBar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </body>
      </UserProvider>

    </html>
  );
}
